"""HTML Report Viewer"""

from pathlib import Path
from typing import Optional

from orp.storage import ORPStorage
from orp.schema import LessonStatus


def _esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace(chr(34), "&quot;"))


class HTMLReporter:
    def __init__(self, storage=None):
        self._storage = storage or ORPStorage()

    def _row(self, e):
        k = e.kind.value
        c = _esc(e.content[:200])
        s = _esc(e.source)
        r = ', '.join(_esc(x) for x in e.evidence_refs[:3])
        out = '<tr>'
        out += '<td class="kind-' + k + '">' + k + '</td>'
        out += '<td>' + s + '</td>'
        out += '<td>' + c + '</td>'
        out += '<td>' + r + '</td>'
        out += '</tr>'
        return out

    def _exp_html(self, exp):
        rows = ''.join(self._row(e) for e in exp.timeline)
        goal = _esc(exp.task.get('goal', '?'))
        eid = _esc(exp.experience_id[:16]) + '...'
        st = _esc(exp.outcome.status)
        ag = _esc(exp.agent.get('id', '?'))
        out = '<div class="card">'
        out += '<h2>' + goal + '</h2>'
        out += '<div class="meta">'
        out += '<span class="tag">ID: ' + eid + '</span>'
        out += '<span class="tag">Status: ' + st + '</span>'
        out += '<span class="tag">Agent: ' + ag + '</span>'
        out += '</div><h3>Timeline</h3><table>'
        out += '<tr><th>Kind</th><th>Source</th><th>Content</th><th>Evidence</th></tr>'
        out += rows + '</table></div>'
        return out

    def _lesson_row(self, l):
        lid = _esc(l.lesson_id[:12]) + '...'
        rec = _esc(l.recommendation[:100])
        sc = 'status-' + l.status.value
        sv = l.status.value
        vl = l.validation.get('level', 'asserted')
        out = '<tr>'
        out += '<td>' + lid + '</td>'
        out += '<td>' + rec + '</td>'
        out += '<td><span class="' + sc + '">' + sv + '</span></td>'
        out += '<td>' + vl + '</td></tr>'
        return out

    def render_report(self, title="ORP Report"):
        exps = self._storage.list_experiences(limit=20)
        lessons = self._storage.list_lessons(limit=20)
        exp_html = ''.join(self._exp_html(e) for e in exps)
        lesson_html = ''.join(self._lesson_row(l) for l in lessons)
        st = _esc(title)
        ec = str(len(exps))
        lc = str(len(lessons))
        ac = str(sum(1 for l in lessons if l.status == LessonStatus.ACTIVE))
        html = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">'
        html += '<title>' + st + '</title><style>'
        html += 'body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:960px;margin:0 auto;padding:20px;background:#f5f5f5;}'
        html += 'h1{color:#333;}.card{background:#fff;border-radius:8px;padding:20px;margin:16px 0;box-shadow:0 1px 3px rgba(0,0,0,0.1);}'
        html += '.meta{margin:8px 0;}.tag{display:inline-block;background:#e0e7ff;padding:2px 8px;border-radius:4px;font-size:12px;margin:2px;}'
        html += 'table{width:100%;border-collapse:collapse;margin:8px 0;}'
        html += 'th,td{text-align:left;padding:6px 8px;border-bottom:1px solid #eee;font-size:13px;}'
        html += 'th{background:#f9fafb;font-weight:600;}'
        html += '.kind-observation{color:#2563eb;}.kind-claim{color:#d97706;}.kind-action{color:#059669;}'
        html += '.kind-outcome{color:#7c3aed;}.kind-feedback{color:#0891b2;}'
        html += '.status-active{color:#059669;font-weight:600;}.status-candidate{color:#d97706;}'
        html += '.status-under_review{color:#dc2626;}.status-deprecated{color:#6b7280;}'
        html += '.stats{display:flex;gap:16px;flex-wrap:wrap;}'
        html += '.stat-box{background:#fff;border-radius:8px;padding:16px;flex:1;min-width:120px;text-align:center;box-shadow:0 1px 3px rgba(0,0,0,0.1);}'
        html += '.stat-value{font-size:28px;font-weight:700;color:#2563eb;}'
        html += '.stat-label{font-size:12px;color:#6b7280;}'
        html += '</style></head><body>'
        html += '<h1>' + st + '</h1>'
        html += '<div class="stats">'
        html += '<div class="stat-box"><div class="stat-value">' + ec + '</div><div class="stat-label">Experiences</div></div>'
        html += '<div class="stat-box"><div class="stat-value">' + lc + '</div><div class="stat-label">Lessons</div></div>'
        html += '<div class="stat-box"><div class="stat-value">' + ac + '</div><div class="stat-label">Active</div></div>'
        html += '</div><h2>Lessons</h2>'
        html += '<div class="card"><table><tr><th>ID</th><th>Recommendation</th><th>Status</th><th>Validation</th></tr>'
        html += lesson_html + '</table></div>'
        html += '<h2>Recent Experiences</h2>'
        html += exp_html
        html += '<p style="color:#999;font-size:12px;text-align:center;margin-top:32px;">Generated by ORP v0.3</p>'
        html += '</body></html>'
        return html

    def write_report(self, path="orp_report.html"):
        Path(path).write_text(self.render_report(), encoding='utf-8')
        return path